### ISSUE TITLE
301 error.

### ISSUE THREAD

**Issue by KT324** [Caphyon/advinst-vsts-tool#1]
Running into an issue running this build on the Hosted instance in VSTS. 

![image](https://user-images.githubusercontent.com/29666975/32450060-3f75f374-c2e1-11e7-8482-597dd5785894.png)

**Comment by fernandoNeurallabs** [comment]
I have the same issue with 14.0.2 or 14.0. both options works directly on a browser
![image](https://user-images.githubusercontent.com/33428205/32453115-bc6afb88-c31b-11e7-989c-cd2b25732985.png)

**Comment by burcadoruciprian** [comment]
This is because advanced installer download URL move to https. Fixed it. Please update

**Comment by fernandoNeurallabs** [comment]
It works!

Many thanks!

**Comment by KT324** [comment]
Working on my end as well. Thanks for the update!
