### ISSUE TITLE
Migrate Azure DevOps task for Advanced Installer to Node 10

### ISSUE THREAD

**Issue by Eusebyu1** [Caphyon/advinst-vsts-tool#10]
The below warning is displayed when building an Advanced Installer project from Azure DevOps, so we need to migrate to Node 10 before March 31st 2022:

[https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/migrateNode10.md](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/migrateNode10.md)

`##[warning]This task uses Node 6 execution handler, which will be removed March 31st 2022. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10) (check this page also if you would like to disable Node 6 deprecation warnings). If you are the user - feel free to reach out to the owners of this task to proceed on migration.`

**Comment by burcadoruciprian** [comment]
Migrated both [advinst-vsts-tool](https://github.com/Caphyon/advinst-vsts-tool) and [advinst-vsts-task](https://github.com/Caphyon/advinst-vsts-task)
