### ISSUE TITLE
Installer Task fails with "Unhandled: %1 is not a valid Win32 application."

### ISSUE THREAD

**Issue by SardaukarOnLine** [Caphyon/advinst-vsts-tool#3]
In a Hosted VS2017 scenario we've created a new build with the minimum steps just to test the Advanced Installer Build.

When we run the "Advanced Installer Tool Installer" specifying the LicenseKey and the Advanced Installer version (or not, we test it both ways), we receive the following error:

> ##[section]Starting: Use Advanced Installer 
==============================================================================
Task         : Advanced Installer Tool Installer
Description  : Acquires a specific version of Advanced Installer from internet or the tools cache and adds it to the PATH. Use this task to install Advanced Installer for subsequent tasks
Version      : 1.1.0
Author       : Caphyon
Help         : 
==============================================================================
##[error]Unhandled: %1 is not a valid Win32 application.
\\?\C:\TFSAgents\ag1\_work\_tasks\AdvancedInstallerTool_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\1.1.0\node_modules\winfileinfo\winfileinfo.node
##[error]Unhandled: %1 is not a valid Win32 application.
\\?\C:\TFSAgents\ag1\_work\_tasks\AdvancedInstallerTool_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\1.1.0\node_modules\winfileinfo\winfileinfo.node
##[section]Finishing: Use Advanced Installer 

Any ideas about wich Win32 application is talking about? or what can we configure to use it properly? 

Thanks in advance.

**Comment by racekarl** [comment]
I have this same issue using an On Premises Azure DevOps Server 2019 with an in house 32-bit (x86) VS 2017 build agent.

**Comment by burcadoruciprian** [comment]
Hi,
Sorry for the late reply. The error seems to be related to a **winfileinfo** dependency we are using in our task. We shall investigate this scenario and let you know.

Thanks

**Comment by burcadoruciprian** [comment]
The dependency is built for x64 architecture. It will not work on x86
