### ISSUE TITLE
Azure DevOps build hangs indefinitely if TARGETDIR path contains spaces

### ISSUE THREAD

**Issue by eusebyu123** [Caphyon/advinst-vsts-tool#6]
Azure DevOps build hangs indefinitely on the command below the advinst extract folder contains spaces. This manifests on local hosted clients

C:\Windows\system32\msiexec.exe /a "C:\My Folder\resources" "TARGETDIR=C:\My Folder\resources" /qn

**Comment by burcadoruciprian** [comment]
This issue was fixed in 1.2.3 version
